#Docker compose
version: '3.7'
services:
  principal:
    container_name: principal
    image: principal:0.0.1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    networks:
      - proyecto-app

networks:
  proyecto-app:
    external: true